services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    user: "1000:1000"
    volumes:
      -   ./:/var/www/
    container_name: app
    working_dir: /var/www/
    restart: always
    env_file:
      - .env
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql
  nginx:
    container_name: 'laravel_nginx'
    image: "nginx:stable-alpine"
    restart: "always"
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/
      - ./docker-compose/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

